[app.global]
serviceName = "insight-server"
environment = "prod"

[server.http]
host = "0.0.0.0"
port = 9013
grace = false
HookReq = true
HookRsp = true

[server.httpgovern]
host = "0.0.0.0"
port = 9012

[mysql.default]
dsn = "root@tcp(localhost:3306)/insight-server?charset=utf8&parseTime=True&loc=Local&readTimeout=1s&timeout=1s&writeTimeout=3s"
debug = true
hookReq = true
hookRsp = true

[logger.flygo]
writer = "file"
level = "info"
dir = "/home/www/log/insight-server"

[logger.default]
writer = "file"
level = "info"
dir = "/home/www/log/insight-server"